[package]
name = "blazediff-wasm"
version = "0.7.0"
edition = "2021"
authors = ["Teimur Gasanov <me@teimurjan.dev>"]
description = "Blazing-fast SIMD-optimized WASM implementation of BlazeDiff image comparison algorithm"
license = "MIT"
repository = "https://github.com/teimurjan/blazediff"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2"
js-sys = "0.3"
serde = { version = "1.0", features = ["derive"] }


[profile.release]
# Optimize for speed, not size
opt-level = 3
# Enable link-time optimization
lto = true
# Enable more aggressive optimization 
codegen-units = 1
# Panic = abort for smaller binary size
panic = "abort"

[package.metadata.wasm-pack.profile.release]
# Optimize for size
wee_alloc = false
