import { access, mkdir } from "node:fs/promises";
import path from "node:path";
import { compare, type InterpretResult } from "@blazediff/core-native";
import { DEFAULT_THRESHOLD } from "../defaults";
import { paths } from "../paths";

async function fileExists(p: string): Promise<boolean> {
	try {
		await access(p);
		return true;
	} catch {
		return false;
	}
}

export interface DiffOptions {
	threshold?: number;
	antialiasing?: boolean;
	emitDiffPng?: boolean;
}

export interface DiffOutcome {
	id: string;
	baselinePath: string;
	actualPath: string;
	diffPath?: string;
	match: boolean;
	reason?: "pixel-diff" | "layout-diff" | "file-not-exists";
	diffCount?: number;
	diffPercentage?: number;
	interpretation?: InterpretResult;
}

export async function diffEntry(
	id: string,
	baselinePath: string,
	actualPath: string,
	opts: DiffOptions = {},
	cwd: string = process.cwd(),
): Promise<DiffOutcome> {
	const [hasBaseline, hasActual] = await Promise.all([
		fileExists(baselinePath),
		fileExists(actualPath),
	]);
	if (!hasBaseline || !hasActual) {
		return {
			id,
			baselinePath,
			actualPath,
			match: false,
			reason: "file-not-exists",
		};
	}

	let diffPath: string | undefined;
	if (opts.emitDiffPng) {
		const actualDir = paths(cwd).actual;
		await mkdir(actualDir, { recursive: true });
		diffPath = path.join(actualDir, `${id}.diff.png`);
	}

	const threshold = opts.threshold ?? DEFAULT_THRESHOLD;
	const antialiasing = opts.antialiasing ?? true;

	// Interpret mode returns region analysis but does not write the visual diff
	// PNG, so the output path is generated by a second non-interpret pass below.
	const result = await compare(baselinePath, actualPath, undefined, {
		threshold,
		antialiasing,
		interpret: true,
	});

	if (result.match) return { id, baselinePath, actualPath, match: true };
	if (result.reason === "file-not-exists") {
		return {
			id,
			baselinePath,
			actualPath,
			match: false,
			reason: "file-not-exists",
		};
	}
	if (result.reason === "layout-diff") {
		return {
			id,
			baselinePath,
			actualPath,
			diffPath,
			match: false,
			reason: "layout-diff",
		};
	}

	// Emit the visual diff PNG (red-overlay) so the report can show it on failure.
	// Compress it: the diff is mostly background with sparse changes, and the
	// report inlines it as base64, so the native default (compression 0) bloats.
	if (diffPath) {
		await compare(baselinePath, actualPath, diffPath, {
			threshold,
			antialiasing,
			compression: 9,
		});
	}

	return {
		id,
		baselinePath,
		actualPath,
		diffPath,
		match: false,
		reason: "pixel-diff",
		diffCount: result.diffCount,
		diffPercentage: result.diffPercentage,
		interpretation: result.interpretation,
	};
}
