import { envVarsForPersona } from "./env";

export interface PostprocessOptions {
	persona: string;
	loginUrl: string;
}

export interface PostprocessResult {
	source: string;
	warnings: string[];
	rewroteEmail: boolean;
	rewrotePassword: boolean;
}

const POSITIONAL_RE = /:nth-child\(|:nth-of-type\(|\s>\s/;
const EMAIL_RE = /\b(email|username|user_?name)\b/;
const PASSWORD_RE = /\bpassword\b/;

function normalizeSelector(selector: string): string {
	return selector.toLowerCase().replace(/['"`]/g, "");
}

function looksLikeEmail(selector: string): boolean {
	return EMAIL_RE.test(normalizeSelector(selector));
}

function looksLikePassword(selector: string): boolean {
	return PASSWORD_RE.test(normalizeSelector(selector));
}

function selectorIsPositional(selector: string): boolean {
	return POSITIONAL_RE.test(selector);
}

function escapeForRegex(s: string): string {
	return s.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}

interface FillCall {
	full: string;
	selector: string;
	value: string;
	quote: string;
}

const FILL_RE =
	/await\s+page(?:\.getByLabel\(([^)]*)\)|\.getByPlaceholder\(([^)]*)\)|\.locator\(([^)]*)\))?\s*\.fill\((['"`])((?:\\.|(?!\4)[^\\])*)\4\)/g;

function* iterateFills(source: string): Generator<FillCall> {
	const re = new RegExp(FILL_RE.source, "g");
	let m: RegExpExecArray | null = re.exec(source);
	while (m !== null) {
		const selector = (m[1] ?? "") + (m[2] ?? "") + (m[3] ?? "");
		yield {
			full: m[0],
			selector: selector.replace(/^['"`]|['"`]$/g, ""),
			value: m[5],
			quote: m[4],
		};
		m = re.exec(source);
	}
}

function extractActionBody(source: string): { body: string; found: boolean } {
	const markers = [
		"async ({ page }) => {",
		"async ({page}) => {",
		"async function run(page) {",
		"async function login(page) {",
	];
	for (const marker of markers) {
		const start = source.indexOf(marker);
		if (start === -1) continue;
		const open = start + marker.length;
		let depth = 1;
		let i = open;
		while (i < source.length && depth > 0) {
			const c = source[i];
			if (c === "{") depth += 1;
			else if (c === "}") depth -= 1;
			if (depth === 0) break;
			i += 1;
		}
		if (depth === 0) {
			return { body: source.slice(open, i).trim(), found: true };
		}
	}
	const lines = source.split("\n").filter((l) => /^\s*await\s+page\./.test(l));
	if (lines.length > 0) {
		return { body: lines.join("\n").trim(), found: true };
	}
	return { body: "", found: false };
}

function indent(body: string, prefix: string): string {
	return body
		.split("\n")
		.map((line) => (line.length > 0 ? prefix + line : line))
		.join("\n");
}

export function postprocessCodegen(
	rawCodegen: string,
	opts: PostprocessOptions,
): PostprocessResult {
	const warnings: string[] = [];
	const extracted = extractActionBody(rawCodegen);
	if (!extracted.found) {
		warnings.push(
			"could not parse codegen output — wrote raw actions; please review .blazediff/harnesses/auth.js",
		);
	}
	let body = (extracted.body || rawCodegen.trim()).replace(
		/^\s*await\s+page\.goto\([^)]*\)\s*;?\s*\n?/,
		"",
	);

	let rewroteEmail = false;
	let rewrotePassword = false;
	let sawPositional = false;

	const fills = Array.from(iterateFills(body));
	for (const call of fills) {
		if (selectorIsPositional(call.selector)) sawPositional = true;
		const isPassword = looksLikePassword(call.selector);
		const isEmail = !isPassword && looksLikeEmail(call.selector);
		if (!isPassword && !isEmail) continue;
		const replacement = call.full.replace(
			new RegExp(
				`(${escapeForRegex(call.quote)})${escapeForRegex(call.value)}(${escapeForRegex(call.quote)})`,
			),
			isPassword ? "password" : "email",
		);
		body = body.replace(call.full, replacement);
		if (isPassword) rewrotePassword = true;
		else rewroteEmail = true;
	}

	if (sawPositional) {
		warnings.push(
			"codegen used positional selectors (e.g. nth-child). Review and replace with attribute selectors for stability.",
		);
	}
	if (!rewroteEmail) {
		warnings.push(
			"no email/username field detected — the harness will not read BLAZEDIFF_AUTH_*_EMAIL. Edit the file by hand if needed.",
		);
	}
	if (!rewrotePassword) {
		warnings.push(
			"no password field detected — the harness will not read BLAZEDIFF_AUTH_*_PASSWORD. Edit the file by hand if needed.",
		);
	}

	const { email, password } = envVarsForPersona(opts.persona);
	const loginUrlJson = JSON.stringify(opts.loginUrl);
	const personaJson = JSON.stringify(opts.persona);

	const source = `// Generated by \`blazediff-agent auth init\`.
// A login harness: attach it to an entry via harnesses: [{ name: "auth", params: { persona } }].
// Credentials live in env vars (e.g. ${email}, ${password}).
// Each persona reads BLAZEDIFF_AUTH_<PERSONA>_EMAIL / _PASSWORD.

/** @type {import("@blazediff/agent").Harness<{ persona?: string }>} */
export default {
	phase: "setup",
	async run({ page, params }) {
		const persona = params.persona ?? ${personaJson};
		const upper = persona.toUpperCase().replace(/[^A-Z0-9]/g, "_");
		const email = process.env[\`BLAZEDIFF_AUTH_\${upper}_EMAIL\`];
		const password = process.env[\`BLAZEDIFF_AUTH_\${upper}_PASSWORD\`];
		if (!email || !password) {
			throw new Error(
				\`missing BLAZEDIFF_AUTH_\${upper}_EMAIL / _PASSWORD env vars for persona "\${persona}"\`,
			);
		}
		await page.goto(${loginUrlJson});
${indent(body, "\t\t")}
		if (new URL(page.url()).pathname === new URL(${loginUrlJson}).pathname) {
			throw new Error(
				"login harness finished but the page is still on the login URL — check the form submits and waits for redirect",
			);
		}
	},
};
`;

	return { source, warnings, rewroteEmail, rewrotePassword };
}
