[build]
target = "wasm32-unknown-unknown"

[target.wasm32-unknown-unknown]
rustflags = [
  "-C", "target-feature=+simd128",
  "-C", "target-feature=+relaxed-simd",
  "-C", "target-feature=+nontrapping-fptoint", 
  "-C", "target-feature=+sign-ext",
  "-C", "target-feature=+bulk-memory"
]
