/**
 * Turns Playwright `codegen` output into a BlazeDiff harness module. A recording
 * is the same shape for any flow — a sequence of `await page.…` actions — so the
 * generic builder ({@link buildHarness}) just wraps the recorded body. The login
 * flavor ({@link buildLoginHarness}) additionally rewrites typed credentials to
 * env-var references so secrets never land in the file.
 */

export const DEFAULT_PERSONA = "default";

/**
 * Env var names a login harness reads for a persona. Used by the recorder to
 * tell the user which vars to set; the harness itself reads them at runtime.
 */
export function envVarsForPersona(persona: string): {
	email: string;
	password: string;
} {
	const upper = persona.toUpperCase().replace(/[^A-Z0-9]/g, "_");
	return {
		email: `BLAZEDIFF_AUTH_${upper}_EMAIL`,
		password: `BLAZEDIFF_AUTH_${upper}_PASSWORD`,
	};
}

export interface BuildHarnessResult {
	source: string;
	warnings: string[];
}

export interface LoginHarnessResult extends BuildHarnessResult {
	rewroteEmail: boolean;
	rewrotePassword: boolean;
}

const BANNER = "// Generated by `blazediff-agent harness record`.";

const POSITIONAL_RE = /:nth-child\(|:nth-of-type\(|\s>\s/;
const EMAIL_RE = /\b(email|username|user_?name)\b/;
const PASSWORD_RE = /\bpassword\b/;

function normalizeSelector(selector: string): string {
	return selector.toLowerCase().replace(/['"`]/g, "");
}

function looksLikeEmail(selector: string): boolean {
	return EMAIL_RE.test(normalizeSelector(selector));
}

function looksLikePassword(selector: string): boolean {
	return PASSWORD_RE.test(normalizeSelector(selector));
}

function selectorIsPositional(selector: string): boolean {
	return POSITIONAL_RE.test(selector);
}

function escapeForRegex(s: string): string {
	return s.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}

interface FillCall {
	full: string;
	selector: string;
	value: string;
	quote: string;
}

const FILL_RE =
	/await\s+page(?:\.getByLabel\(([^)]*)\)|\.getByPlaceholder\(([^)]*)\)|\.locator\(([^)]*)\))?\s*\.fill\((['"`])((?:\\.|(?!\4)[^\\])*)\4\)/g;

function* iterateFills(source: string): Generator<FillCall> {
	const re = new RegExp(FILL_RE.source, "g");
	let m: RegExpExecArray | null = re.exec(source);
	while (m !== null) {
		const selector = (m[1] ?? "") + (m[2] ?? "") + (m[3] ?? "");
		yield {
			full: m[0],
			selector: selector.replace(/^['"`]|['"`]$/g, ""),
			value: m[5],
			quote: m[4],
		};
		m = re.exec(source);
	}
}

function extractActionBody(source: string): { body: string; found: boolean } {
	const markers = [
		"async ({ page }) => {",
		"async ({page}) => {",
		"async function run(page) {",
		"async function login(page) {",
	];
	for (const marker of markers) {
		const start = source.indexOf(marker);
		if (start === -1) continue;
		const open = start + marker.length;
		let depth = 1;
		let i = open;
		while (i < source.length && depth > 0) {
			const c = source[i];
			if (c === "{") depth += 1;
			else if (c === "}") depth -= 1;
			if (depth === 0) break;
			i += 1;
		}
		if (depth === 0) {
			return { body: source.slice(open, i).trim(), found: true };
		}
	}
	const lines = source.split("\n").filter((l) => /^\s*await\s+page\./.test(l));
	if (lines.length > 0) {
		return { body: lines.join("\n").trim(), found: true };
	}
	return { body: "", found: false };
}

/** Drop the leading `page.goto(...)` — the harness navigates explicitly. */
function stripLeadingGoto(body: string): string {
	return body.replace(/^\s*await\s+page\.goto\([^)]*\)\s*;?\s*\n?/, "");
}

function indent(body: string, prefix: string): string {
	return body
		.split("\n")
		.map((line) => (line.length > 0 ? prefix + line : line))
		.join("\n");
}

/** Parse the recorded actions, warning (not throwing) when the shape is novel. */
function actionBody(
	rawCodegen: string,
	name: string,
	warnings: string[],
): string {
	const extracted = extractActionBody(rawCodegen);
	if (!extracted.found) {
		warnings.push(
			`could not parse codegen output — wrote raw actions; please review .blazediff/harnesses/${name}.js`,
		);
	}
	return stripLeadingGoto(extracted.body || rawCodegen.trim());
}

/**
 * Build a generic interaction/setup harness from a recording. The recorded body
 * runs after the harness navigates to `url`.
 */
export function buildHarness(
	rawCodegen: string,
	opts: { name: string; url: string; phase: "setup" | "interact" },
): BuildHarnessResult {
	const warnings: string[] = [];
	const body = actionBody(rawCodegen, opts.name, warnings);
	const urlJson = JSON.stringify(opts.url);

	const source = `${BANNER}
// Attach it to an entry via harnesses: [{ name: ${JSON.stringify(opts.name)} }].

/** @type {import("@blazediff/agent").Harness} */
export default {
	phase: "${opts.phase}",
	async run({ page }) {
		await page.goto(${urlJson});
${indent(body, "\t\t")}
	},
};
`;
	return { source, warnings };
}

/**
 * Build a login (`phase:"setup"`) harness: rewrite the typed email/password to
 * `BLAZEDIFF_AUTH_<PERSONA>_*` env refs and assert the page left the login URL.
 */
export function buildLoginHarness(
	rawCodegen: string,
	opts: { name: string; loginUrl: string; persona: string },
): LoginHarnessResult {
	const warnings: string[] = [];
	let body = actionBody(rawCodegen, opts.name, warnings);

	let rewroteEmail = false;
	let rewrotePassword = false;
	let sawPositional = false;

	for (const call of Array.from(iterateFills(body))) {
		if (selectorIsPositional(call.selector)) sawPositional = true;
		const isPassword = looksLikePassword(call.selector);
		const isEmail = !isPassword && looksLikeEmail(call.selector);
		if (!isPassword && !isEmail) continue;
		const replacement = call.full.replace(
			new RegExp(
				`(${escapeForRegex(call.quote)})${escapeForRegex(call.value)}(${escapeForRegex(call.quote)})`,
			),
			isPassword ? "password" : "email",
		);
		body = body.replace(call.full, replacement);
		if (isPassword) rewrotePassword = true;
		else rewroteEmail = true;
	}

	if (sawPositional) {
		warnings.push(
			"codegen used positional selectors (e.g. nth-child). Review and replace with attribute selectors for stability.",
		);
	}
	if (!rewroteEmail) {
		warnings.push(
			"no email/username field detected — the harness will not read BLAZEDIFF_AUTH_*_EMAIL. Edit the file by hand if needed.",
		);
	}
	if (!rewrotePassword) {
		warnings.push(
			"no password field detected — the harness will not read BLAZEDIFF_AUTH_*_PASSWORD. Edit the file by hand if needed.",
		);
	}

	const { email, password } = envVarsForPersona(opts.persona);
	const loginUrlJson = JSON.stringify(opts.loginUrl);
	const personaJson = JSON.stringify(opts.persona);

	const source = `${BANNER}
// A login harness: attach it to an entry via harnesses: [{ name: ${JSON.stringify(opts.name)}, params: { persona } }].
// Credentials live in env vars (e.g. ${email}, ${password}).
// Each persona reads BLAZEDIFF_AUTH_<PERSONA>_EMAIL / _PASSWORD.

import { assertLeftLoginPage } from "@blazediff/agent";

/** @type {import("@blazediff/agent").Harness<{ persona?: string }>} */
export default {
	phase: "setup",
	async run({ page, params }) {
		const persona = params.persona ?? ${personaJson};
		const upper = persona.toUpperCase().replace(/[^A-Z0-9]/g, "_");
		const email = process.env[\`BLAZEDIFF_AUTH_\${upper}_EMAIL\`];
		const password = process.env[\`BLAZEDIFF_AUTH_\${upper}_PASSWORD\`];
		if (!email || !password) {
			throw new Error(
				\`missing BLAZEDIFF_AUTH_\${upper}_EMAIL / _PASSWORD env vars for persona "\${persona}"\`,
			);
		}
		await page.goto(${loginUrlJson});
${indent(body, "\t\t")}
		await assertLeftLoginPage(page, ${loginUrlJson});
	},
};
`;

	return { source, warnings, rewroteEmail, rewrotePassword };
}
