name: Benchmark

on:
  push:
    branches:
      - main
    paths:
      - 'packages/**'
      - 'package.json'
      - 'pnpm-lock.yaml'
      - '.github/workflows/benchmark.yml'

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Benchmark
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version-file: '.node-version'

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: Run Benchmark
        run: pnpm benchmark --iterations=50 --target=core

      - name: Run Benchmark (bin)
        run: pnpm benchmark --iterations=50 --target=bin
