name: Benchmark

on:
  push:
    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Benchmark
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: Build Packages
        run: pnpm build

      - name: Install Dependencies Again (after bin is built)
        run: pnpm install --frozen-lockfile

      - name: Run Benchmark
        run: pnpm benchmark --iterations=10 --target=core

      - name: Run Benchmark (bin)
        run: pnpm benchmark --iterations=10 --target=bin

      - name: Run Benchmark (antialiasing)
        run: pnpm benchmark --iterations=10000 --target=antialiasing
