name: Benchmark SSIM

on:
  push:
    branches:
      - main

concurrency: ${{ github.workflow }}

jobs:
  benchmark-ssim:
    name: SSIM Benchmark
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v5

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version-file: ".node-version"
          cache: "pnpm"

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: Build
        run: pnpm build

      - name: Run Benchmark (blazediff)
        run: pnpm benchmark:hitchhikers-ssim -- --format=json --output=ssim.json

      - name: Run Benchmark (ssim.js)
        run: pnpm benchmark:weber-ssim.js -- --format=json --output=ssim-js.json

      - name: Compare and Print Combined Markdown Table (algorithm)
        if: always()
        run: node .github/workflows/scripts/compare-and-print-ssim.js
